/**
 * Generated by `npm run pictures` — do not edit.
 *
 * Maps `<lesson>/<item>` to the picture that shows it. An item missing from here is
 * drawn as its emoji instead, which is what lets a lesson be illustrated one at a time
 * (design D94).
 */
export const PICTURE_DIR = '/pics'

export const pictures: Readonly<Record<string, string>> = {
  "animals/bear": 'animals/bear.jpg',
  "animals/bird": 'animals/bird.jpg',
  "animals/cat": 'animals/cat.jpg',
  "animals/dog": 'animals/dog.jpg',
  "animals/duck": 'animals/duck.jpg',
  "animals/elephant": 'animals/elephant.jpg',
  "animals/fish": 'animals/fish.jpg',
  "animals/lion": 'animals/lion.jpg',
  "animals/monkey": 'animals/monkey.jpg',
  "animals/rabbit": 'animals/rabbit.jpg',
  "body-parts/arm": 'body-parts/arm.jpg',
  "body-parts/ears": 'body-parts/ears.jpg',
  "body-parts/eyes": 'body-parts/eyes.jpg',
  "body-parts/foot": 'body-parts/foot.jpg',
  "body-parts/hair": 'body-parts/hair.jpg',
  "body-parts/hand": 'body-parts/hand.jpg',
  "body-parts/leg": 'body-parts/leg.jpg',
  "body-parts/mouth": 'body-parts/mouth.jpg',
  "body-parts/nose": 'body-parts/nose.jpg',
  "body-parts/teeth": 'body-parts/teeth.jpg',
  "colours/black": 'colours/black.svg',
  "colours/blue": 'colours/blue.svg',
  "colours/brown": 'colours/brown.svg',
  "colours/green": 'colours/green.svg',
  "colours/orange": 'colours/orange.svg',
  "colours/pink": 'colours/pink.svg',
  "colours/purple": 'colours/purple.svg',
  "colours/red": 'colours/red.svg',
  "colours/white": 'colours/white.svg',
  "colours/yellow": 'colours/yellow.svg',
  "food/apple": 'food/apple.jpg',
  "food/banana": 'food/banana.jpg',
  "food/bread": 'food/bread.jpg',
  "food/cake": 'food/cake.jpg',
  "food/egg": 'food/egg.jpg',
  "food/ice-cream": 'food/ice-cream.jpg',
  "food/milk": 'food/milk.jpg',
  "food/noodles": 'food/noodles.jpg',
  "food/rice": 'food/rice.jpg',
  "food/water": 'food/water.jpg',
  "shapes/circle": 'shapes/circle.svg',
  "shapes/diamond": 'shapes/diamond.svg',
  "shapes/heart": 'shapes/heart.svg',
  "shapes/oval": 'shapes/oval.svg',
  "shapes/rectangle": 'shapes/rectangle.svg',
  "shapes/square": 'shapes/square.svg',
  "shapes/star": 'shapes/star.svg',
  "shapes/triangle": 'shapes/triangle.svg',
}
